# LEARNING NUMPY

In [1]:
import numpy as np
#CREATING A NORMAL LIST
l=range(100)
print(l)

range(0, 100)


In [2]:
print(len(l))

100


In [8]:
#CREATING A RANGE OG LIST USING NUMPY.
#arange in numpy is similar to range 
k=np.arange(100)
print(len(k))

100


# Basic operations on numpy


# 1. Creating and Accessing 1D and 2D 

In [9]:
arr=np.array([5,6,7])
print(arr[0])
print(arr[1])

5
6


In [18]:
arr1=np.array([[5,6],[1,2],[9,5]])
print(arr[0])
print(arr1.ndim)

#ndim tells the dimension of thee array 

5
2


In [19]:
# Tels the bits consumed by the items
arr1.itemsize

4

In [20]:
#tells the Data Type of the array
arr1.dtype

dtype('int32')

In [21]:
#tells the rows and columns
arr1.shape

(3, 2)

# Numpy Functions

In [22]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
 np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
#creates the array with the specified range
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [26]:
#re shapes the existing array
arr1.reshape(2,3)

array([[5, 6, 1],
       [2, 9, 5]])

In [27]:
#converts to 1Dimensional.
#DOES NOT ALTER THE ORIGINAL ARRAY
arr1.ravel()

array([5, 6, 1, 2, 9, 5])

# MATHEMATICAL FUNCTIONS

In [28]:
#provides the minimum element 
arr1.min()

1

In [87]:
print(arr)
print(arr+2)
print(arr-2)
print(arr*2)

[5 6 7]
[7 8 9]
[3 4 5]
[10 12 14]


In [29]:
#provides the maximum element 
arr1.max()

9

In [92]:
#Matrix multiplication
d=np.zeros((3,2))
e=np.full((2,3),2)
np.matmul(d,e)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#provides the sum of all the elements in the array
arr1.sum()

28

In [31]:
np.sqrt(arr1)

array([[2.23606798, 2.44948974],
       [1.        , 1.41421356],
       [3.        , 2.23606798]])

In [32]:
#tells the total bytes or the total size of the array
arr1.nbytes

24

# Accessing/Changing elements,rows,columns etc

array([7, 8, 9])

In [33]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
a.shape

(2, 7)

In [37]:
#Getting a specific element[row,column]
a[1,5]

13

In [39]:
#Getting a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
#getting a specific column
a[:,2]

array([ 3, 10])

In [42]:
#Changing a specific number
a[0,5]=49
a

array([[ 1,  2,  3,  4,  5, 49,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [44]:
#changing a row 
a[0]=[7,6,5,4,3,2,1]
a

array([[ 7,  6,  5,  4,  3,  2,  1],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [46]:
#changing a column
a[:,1]=[98,89]
a

array([[ 7, 98,  5,  4,  3,  2,  1],
       [ 8, 89, 10, 11, 12, 13, 14]])

In [49]:
#Filling the array with another number
np.full((2,2),111,dtype="float")

array([[111., 111.],
       [111., 111.]])

In [50]:
#Creating a matrix of random decimal number
np.random.rand(2,5)

array([[0.02445715, 0.5285362 , 0.76802858, 0.14645907, 0.2339685 ],
       [0.41337073, 0.45860422, 0.562369  , 0.78209502, 0.95671806]])

In [51]:
##Creating a matrix of random intger number
np.random.randint(10,size=(5,5))


array([[7, 0, 4, 9, 6],
       [5, 3, 2, 6, 0],
       [8, 4, 4, 9, 2],
       [5, 0, 1, 4, 9],
       [0, 8, 2, 2, 5]])

In [56]:
#Excercise to  alter an 5*5 matrix
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
z=np.zeros((3,3))
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [77]:
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
b=np.array([1,5,6])
c=b.copy()
c[0]=4
print(c)
print(b)

[4 5 6]
[1 5 6]


# Statistics

In [93]:
#This includes functions like finding min and max that is done already.


# Vertical Stacking

In [96]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack((v1,v2,v1,v1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3]])

# Horizontal stacking

In [97]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.hstack((v1,v2,v1,v1))

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 1, 2, 3])

# Column Stacking

In [101]:
np.column_stack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy intersect and difference

In [102]:
#Find the intersection of two arrays.
np.intersect1d(arr,arr1)

array([5, 6])

In [104]:
#find the difference among 2 numpy arrays.
np.setdiff1d(arr,arr1)

array([7])

# Addition of numpy arrays

In [109]:
n1=np.array([10,20])
n2=np.array([20,30])
np.sum([n1,n2])

80

In [110]:
#Adds only the rows
np.sum([n1,n2],axis=0)

array([30, 50])

# Mean,Median And Standard Deviation

In [111]:
np.mean(n1)

15.0

In [112]:
np.median(n2)

25.0

In [113]:
np.std(n1)

5.0

# Transpose Matrix

In [114]:
n1.transpose()

array([10, 20])